from initiate_key import rsa_key
from initiate_key import weak_key
from encrypt import rsa_enc
from decrypt import rsa_dec
from decrypt import weak_dec
import tkinter as tk

crypto_mode = ""
def setup(mode):
    mode = mode[0]
    global crypto_mode
    if mode == 0:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        file_frame.pack(fill="both")
        file_label.config(text="Filepath/s to the file/s to encrypt")
        file_label.pack()
        file_instructions.pack()
        file_input.pack(fill='x')
        passcode_frame.pack(fill="both")
        passcode_label.config(text="Set private key passcode")
        passcode_label.pack()
        passcode_instructions.config(text="CRITICAL: DO NOT FORGET YOUR PASSCODE.\nWITHOUT IT, YOUR DATA WILL BE LOST.")
        passcode_instructions.pack()
        passcode_input.pack(fill='x')
        save.pack(fill="both")
        save_label.config(text="Save location for keys")
        save_label.pack()
        save_instructions.config(text="Save the keys to an empty folder, and store them somewhere secure\nIf other key files exist in the same folder, they will be overwritten")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Encrypt file/s")
        submit.pack(pady="10")
        crypto_mode = "key_enc"
    elif mode == 1:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        file_frame.pack(fill="both")
        file_label.config(text="Filepath/s to the file/s to encrypt")
        file_label.pack()
        file_instructions.pack()
        file_input.pack(fill='x')
        save.pack(fill="both")
        save_label.config(text="Save location for keys")
        save_label.pack()
        save_instructions.config(text="Save the keys to an empty folder, and store them somewhere secure\nIf other key files exist in the same folder, they will be overwritten")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Encrypt file/s")
        submit.pack(pady="10")
        crypto_mode = "weak_key_enc"
    elif mode == 2:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        file_frame.pack(fill="both")
        file_label.config(text="Filepath/s to the file/s to encrypt")
        file_label.pack()
        file_instructions.pack()
        file_input.pack(fill='x')
        save.pack(fill="both")
        save_label.config(text="Key location")
        save_label.pack()
        save_instructions.config(text="Filepath to matching key trio")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Encrypt file/s")
        submit.pack(pady="10")
        crypto_mode = "enc"
    elif mode == 3:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        file_frame.pack(fill="both")
        file_label.config(text="Filepath/s to the file/s to decrypt")
        file_label.pack()
        file_instructions.pack()
        file_input.pack(fill='x')
        passcode_frame.pack(fill="both")
        passcode_label.config(text="Private key passcode")
        passcode_label.pack()
        passcode_instructions.config(text="Passcode must be the same passcode used when the keys were created")
        passcode_instructions.pack()
        passcode_input.pack(fill='x')
        save.pack(fill="both")
        save_label.config(text="Key location")
        save_label.pack()
        save_instructions.config(text="Filepath to matching key trio")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Decrypt file/s")
        submit.pack(pady="10")
        crypto_mode = "dec"
    elif mode == 4:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        file_frame.pack(fill="both")
        file_label.config(text="Filepath/s to the file/s to decrypt")
        file_label.pack()
        file_instructions.pack()
        file_input.pack(fill='x')
        save.pack(fill="both")
        save_label.config(text="Key location")
        save_label.pack()
        save_instructions.config(text="Filepath to matching key trio")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Decrypt file/s")
        submit.pack(pady="10")
        crypto_mode = "weak_dec"
    elif mode == 5:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        passcode_frame.pack(fill="both")
        passcode_label.config(text="Set private key passcode")
        passcode_label.pack()
        passcode_instructions.config(text="CRITICAL: DO NOT FORGET YOUR PASSCODE.\nWITHOUT IT, YOUR DATA WILL BE LOST.")
        passcode_instructions.pack()
        passcode_input.pack(fill='x')
        save.pack(fill="both")
        save_label.config(text="Save location for keys")
        save_label.pack()
        save_instructions.config(text="Save the keys to an empty folder, and store them somewhere secure\nIf other key files exist in the same folder, they will be overwritten")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Create keys")
        submit.pack(pady="10")
        crypto_mode = "just_key"
    elif mode == 6:
        file_frame.pack_forget()
        file_label.pack_forget()
        file_instructions.pack_forget()
        file_input.pack_forget()
        passcode_frame.pack_forget()
        passcode_label.pack_forget()
        passcode_instructions.pack_forget()
        passcode_input.pack_forget()
        save.pack_forget()
        save_label.pack_forget()
        save_instructions.pack_forget()
        save_input.pack_forget()
        submit.pack_forget()
        save.pack(fill="both")
        save_label.config(text="Save location for keys")
        save_label.pack()
        save_instructions.config(text="Save the keys to an empty folder, and store them somewhere secure\nIf other key files exist in the same folder, they will be overwritten")
        save_instructions.pack()
        save_input.pack(fill="both")
        submit.config(text="Create keys")
        submit.pack(pady="10")
        crypto_mode = "weak_key"

def go(mode, save_folder, target_file, passkey=None):
    if mode == "key_enc":
        rsa_key(passkey, save_folder)
        rsa_enc(target_file, save_folder)
    elif mode == "weak_key_enc":
        weak_key(save_folder)
        rsa_enc(target_file, save_folder)
    elif mode == "enc":
        rsa_enc(target_file, save_folder)
    elif mode == "dec":
        rsa_dec(target_file, save_folder, passkey)
    elif mode == "weak_dec":
        weak_dec(target_file, save_folder)
    elif mode == "just_key":
        rsa_key(passkey, save_folder)
    elif mode == "weak_key":
        weak_key(save_folder)

root = tk.Tk()
root.wm_title("figENC")
canvas = tk.Canvas(root, height=700, width=650)
canvas.pack()
frame = tk.Frame(root, bg="#1A181C")
frame.place(relwidth=1, relheight=1)

header = tk.Label(frame, text="figENC", justify="center", font=("Arial", "24"), bg="#643181", fg="#B494C7")
subheader = tk.Label(frame, text="Industry leading encryption by FIGBERT", justify="center", font=("Arial", "18"), bg="#643181", fg="#B494C7", pady="5")
header.pack(fill="x", side="top")
subheader.pack(fill="x", side="top")

action = tk.Frame(frame, bg="#1A181C", pady="5")
action.pack(fill='both')
action_label = tk.Label(action, text="Action:", justify='left', font=("Arial", "14"), bg="#1A181C", fg="#ACA0B2")
action_label.pack()
action_list = tk.Listbox(action, selectmode="single", font=("Arial", "12"), height=7, bd=1, relief=tk.SUNKEN, bg="#1A181C", fg="#B494C7", selectbackground="#643181")
action_list.insert(1, "Encrypt with fresh keys (password locked)")
action_list.insert(2, "Encrypt with fresh keys (no password)")
action_list.insert(3, "Encrypt with generated keys")
action_list.insert(4, "Decrypt with generated keys (password locked)")
action_list.insert(5, "Decrypt with generated keys (no password)")
action_list.insert(6, "Only create fresh keys (password locked)")
action_list.insert(7, "Only create fresh keys (no password)")
action_list.pack(fill='both', pady="10")
submit_action = tk.Button(action, text="Begin Process", font=("Arial", "12"), command=lambda: setup(action_list.curselection()), bg="#643181", fg="#B494C7")
submit_action.pack()

step_two = tk.Frame(frame, bg="#1A181C")
step_two.pack(fill="both")

file_frame = tk.Frame(step_two, bg="#1A181C", pady="8")
file_label = tk.Label(file_frame, text="If you see this, the app broke", font=("Arial", "14"), bg="#1A181C", fg="#ACA0B2")
file_instructions = tk.Label(file_frame, text="Separate filepaths with colons (:)", font=("Arial", "11"), bg="#1A181C", fg="#B494C7")
file_input = tk.Entry(file_frame, font=("Arial", "12"), justify=tk.CENTER, textvariable=tk.StringVar, relief=tk.SUNKEN, bg="#1A181C", fg="#ACA0B2")
passcode_frame = tk.Frame(step_two, bg="#1A181C", pady="8")
passcode_label = tk.Label(passcode_frame, text="If you see this, the app broke", font=("Arial", "14"), bg="#1A181C", fg="#ACA0B2")
passcode_instructions = tk.Label(passcode_frame, text="If you see this, the app broke", font=("Arial", "11"), bg="#1A181C", fg="#B494C7")
passcode_input = tk.Entry(passcode_frame, font=("Arial", "12"), justify=tk.CENTER, textvariable=tk.StringVar, relief=tk.SUNKEN, bg="#1A181C", fg="#ACA0B2", show="*")

save = tk.Frame(step_two, bg="#1A181C", pady="8")
save_label = tk.Label(save, text="Save location for keys", font=("Arial", "14"), bg="#1A181C", fg="#ACA0B2")
save_instructions = tk.Label(save, text="Save the keys to an empty folder, and store them somewhere secure\nIf other key files exist in the same folder, they will be overwritten", font=("Arial", "11"), bg="#1A181C", fg="#B494C7")
save_input = tk.Entry(save, font=("Arial", "12"), justify=tk.CENTER, textvariable=tk.StringVar, relief=tk.SUNKEN, bg="#1A181C", fg="#ACA0B2")
submit = tk.Button(save, text="If you see this, the app broke", font=("Arial", "12"), command=lambda: go(mode=crypto_mode, save_folder=save_input.get(), target_file=file_input.get(), passkey=passcode_input.get()), bg="#643181", fg="#B494C7")

root.mainloop()